// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormElementController from "./form_element_controller"
application.register("form-element", FormElementController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
